# Generated by Django 3.1.4 on 2021-01-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=50)),
                ('blog', models.TextField()),
            ],
        ),
    ]
