# Generated by Django 3.1.4 on 2021-01-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='blogslug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.TextField(max_length=50),
        ),
    ]
