# Generated by Django 3.1.4 on 2020-12-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtally', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mt', models.IntegerField()),
                ('Zt', models.IntegerField()),
                ('Ot', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tally',
            name='Mt',
        ),
        migrations.RemoveField(
            model_name='tally',
            name='Zt',
        ),
    ]
