# Generated by Django 3.1.4 on 2020-12-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtally', '0002_auto_20201231_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Totals',
            new_name='Total',
        ),
    ]
