# Generated by Django 3.1.4 on 2020-12-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtally', '0003_auto_20201231_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tally',
            name='user',
        ),
        migrations.AddField(
            model_name='tally',
            name='l_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tally',
            name='w_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tally',
            name='winner',
            field=models.CharField(choices=[('M', 'Madelyne'), ('Z', 'Zach')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tally',
            name='game',
            field=models.CharField(choices=[('U', 'Uno'), ('P', 'Pandemic'), ('S', 'Scrabble')], max_length=1),
        ),
    ]
