# Generated by Django 3.1.4 on 2020-12-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtally', '0004_auto_20201231_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='l_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tally',
            name='w_score',
            field=models.IntegerField(null=True),
        ),
    ]
