# Generated by Django 3.1.4 on 2021-01-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtally', '0005_auto_20201231_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
