# Generated by Django 3.1.4 on 2021-01-17 20:05

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_made', models.DateField(auto_now_add=True)),
                ('renewal', models.DateField()),
                ('summary', models.TextField(max_length=300)),
                ('detail', models.TextField()),
                ('f', models.FileField(upload_to='')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['date_made'],
            },
        ),
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('desc', models.CharField(max_length=75)),
                ('DS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcms.dataset')),
            ],
        ),
    ]
